# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20160812_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
