# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_num', models.FileField(upload_to='./upload')),
                ('location', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('identify', models.IntegerField()),
            ],
        ),
    ]
