# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 07:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_auto_20160928_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='num',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 28, 7, 32, 25, 473822, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
