# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_auto_20160928_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
