# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pun_date',
            new_name='pub_date',
        ),
    ]
