# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='isMedium',
        ),
        migrations.RemoveField(
            model_name='house',
            name='name',
        ),
        migrations.RemoveField(
            model_name='house',
            name='username',
        ),
    ]
