# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('area', models.FloatField()),
                ('description', models.TextField()),
                ('picpath', models.FilePathField()),
                ('time', models.DateField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NormlHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('area', models.FloatField()),
                ('description', models.TextField()),
                ('picpath', models.FilePathField()),
                ('time', models.DateField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
