# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0004_auto_20161207_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumhouse',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
