# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0005_auto_20161208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalhouse',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
