# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0006_auto_20161208_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumhouse',
            name='isCheck',
            field=models.BooleanField(default=False),
        ),
    ]
