# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0007_mediumhouse_ischeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('isMedium', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='MediumHouse',
            new_name='House',
        ),
        migrations.DeleteModel(
            name='Medium',
        ),
        migrations.DeleteModel(
            name='NormalHouse',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='isCheck',
            new_name='isChecked',
        ),
    ]
