# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0008_auto_20161208_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='isWanted',
            field=models.BooleanField(default=False),
        ),
    ]
