# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0010_auto_20161209_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='isMedium',
            field=models.BooleanField(default=False),
        ),
    ]
