# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0002_auto_20161209_1551'),
        ('HouseRent', '0011_house_ismedium'),
    ]

    operations = [
    ]
