# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseRent', '0016_auto_20161211_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='picpath',
        ),
        migrations.AddField(
            model_name='house',
            name='pic1',
            field=models.CharField(default='static/users/default.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='pic2',
            field=models.CharField(default='static/users/default.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='pic3',
            field=models.CharField(default='static/users/default.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='pic4',
            field=models.CharField(default='static/users/default.jpg', max_length=100),
        ),
    ]
