# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iCHD', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='Anoymous', max_length=22),
            preserve_default=False,
        ),
    ]
